export const string = "<h2>*ngIf Fx</h2><p>Tap anywhere below</p><div (click)=\"hideToggle=!hideToggle\"><fieldset><legend>*ngIf=\"{{!hideToggle}}\"</legend><div *ngIf=\"!hideToggle\" style=\"text-align:center;padding:1em;background-color: #339966;\" [@fadeIn]=\"{value:FxSession.fxForward=='fadeIn' && !hideToggle, params:{time:fxTime}}\" [@fadeInDown]=\"{value:FxSession.fxForward=='fadeInDown' && !hideToggle, params:{time:fxTime}}\" [@fadeInLeft]=\"{value:FxSession.fxForward=='fadeInLeft' && !hideToggle, params:{time:fxTime}}\" [@fadeInRight]=\"{value:FxSession.fxForward=='fadeInRight' && !hideToggle, params:{time:fxTime}}\" [@fadeInUp]=\"{value:FxSession.fxForward=='fadeInUp' && !hideToggle, params:{time:fxTime}}\" [@bounceIn]=\"{value:FxSession.fxForward=='bounceIn' && !hideToggle, params:{time:fxTime}}\" [@bounceInDown]=\"{value:FxSession.fxForward=='bounceInDown' && !hideToggle, params:{time:fxTime}}\" [@bounceInLeft]=\"{value:FxSession.fxForward=='bounceInLeft' && !hideToggle, params:{time:fxTime}}\" [@bounceInRight]=\"{value:FxSession.fxForward=='bounceInRight' && !hideToggle, params:{time:fxTime}}\" [@bounceInUp]=\"{value:FxSession.fxForward=='bounceInUp' && !hideToggle, params:{time:fxTime}}\" [@rotateIn]=\"{value:FxSession.fxForward=='rotateIn' && !hideToggle, params:{time:fxTime}}\" [@rotateInDownLeft]=\"{value:FxSession.fxForward=='rotateInDownLeft' && !hideToggle, params:{time:fxTime}}\" [@rotateInDownRight]=\"{value:FxSession.fxForward=='rotateInDownRight' && !hideToggle, params:{time:fxTime}}\" [@rotateInUpLeft]=\"{value:FxSession.fxForward=='rotateInUpLeft' && !hideToggle, params:{time:fxTime}}\" [@rotateInUpRight]=\"{value:FxSession.fxForward=='rotateInUpRight' && !hideToggle, params:{time:fxTime}}\" [@slideInUp]=\"{value:FxSession.fxForward=='slideInUp' && !hideToggle, params:{time:fxTime}}\" [@slideInDown]=\"{value:FxSession.fxForward=='slideInDown' && !hideToggle, params:{time:fxTime}}\" [@slideInLeft]=\"{value:FxSession.fxForward=='slideInLeft' && !hideToggle, params:{time:fxTime}}\" [@slideInRight]=\"{value:FxSession.fxForward=='slideInRight' && !hideToggle, params:{time:fxTime}}\" [@zoomIn]=\"{value:FxSession.fxForward=='zoomIn' && !hideToggle, params:{time:fxTime}}\" [@zoomInDown]=\"{value:FxSession.fxForward=='zoomInDown' && !hideToggle, params:{time:fxTime}}\" [@zoomInLeft]=\"{value:FxSession.fxForward=='zoomInLeft' && !hideToggle, params:{time:fxTime}}\" [@zoomInRight]=\"{value:FxSession.fxForward=='zoomInRight' && !hideToggle, params:{time:fxTime}}\" [@zoomInUp]=\"{value:FxSession.fxForward=='zoomInUp' && !hideToggle, params:{time:fxTime}}\"><br/>[@{{FxSession.fxForward}}] =&nbsp;"+
"\n&#123;value:{{!hideToggle}}, params:&#123;time:'{{fxTime}}'&#125;&#125;<br/><br/></div></fieldset></div><div style=\"background-color:#CCC;padding:.5em;\"><div style=\"text-align:center;\"><button (click)=\"hideToggle=!hideToggle\">{{ hideToggle ? 'SHOW' : 'hide' }}</button>&nbsp;&nbsp;&nbsp;"+
"\nSpeed:<input [(ngModel)]=\"fxTime\"/>&nbsp;&nbsp;&nbsp;"+
"\nChange above fx Type:&nbsp;<select-fx [(model)]=\"FxSession.fxForward\"> </select-fx></div><p>DETAILS: The above fx example defines:</p><ul><li>An fxType as a trigger name</li><li>A value to ignite animation</li><li>A value to toggle the *ngIf</li><li>A time defintion passed through as fx params</li></ul><h4>Code Sample 1</h4><textarea style=\"width:100%;height:60px;\" wrap=\"off\" readonly=\"readonly\">&lt;div *ngIf=\"boolean\" [@{{FxSession.fxForward}}]=\"boolean\" &gt;"+
"\n  hide show div"+
"\n&lt;/div&gt;</textarea><h4>Code Sample 2</h4><textarea style=\"width:100%;height:100px;\" wrap=\"off\" readonly=\"readonly\">&lt;div"+
"\n  *ngIf=\"boolean\""+
"\n  [@{{FxSession.fxForward}}] = \"&#123;value:boolean, params:&#123;time:'{{fxTime}}'&#125;&#125;\""+
"\n&gt;"+
"\n  hide show div"+
"\n&lt;/div&gt;</textarea></div>"